export const REGISTER_SUCCESS = "REGISTER_SUCCESS";
export const REGISTER_FAIL = "REGISTER_FAIL";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAIL = "LOGIN_FAIL";
export const LOGOUT = "LOGOUT";
export const REQUEST_GET_MUSIC = "REQUEST_GET_MUSIC";
export const GET_MUSIC_SUCCESS = "GET_MUSIC_SUCCESS";
export const GET_MUSIC_FAIL = "GET_MUSIC_FAIL";